#! /bin/bash

function usage() {
    echo "\
Usage: watch-file FILE COMMAND ARG1 ARG2 ...
Run a command when the contents of FILE changes, killing the
process corresponding to the previous command if it is still running.
"
}

file="$1"
if [ -z "$1" ]; then
    usage
    exit 1
fi

if [ $# -lt 3 ]; then
    usage
    exit 1
fi

hash0=""
hash=""
pid=""

shift
while : ; do
    hash=$(md5sum "$file" | cut -f1 -d' ')
    if [ "$hash0" != "$hash" ]; then
        hash0="$hash"
        if test -n "$pid" && kill -0 $pid; then
            kill $pid
            wait $pid 2> /dev/null
        fi
        "$@" &
        pid=$!
    fi
    sleep 1
done
